WeatherExcelStorage.Core/Controllers/WeatherReportController.cs
using Microsoft.AspNetCore.Mvc;
using WeatherExcelStorage.Api.Models.Requests;
using WeatherExcelStorage.Core.Domain.Services;

namespace WeatherExcelStorage.Core.Controllers;

/// <summary>
///     Контроллер отчетов по погоде
/// </summary>
public sealed class WeatherReportController : Controller
{
    private readonly IWeatherReportService _reportService;

    /// <inheritdoc cref="WeatherReportController" />
    public WeatherReportController(IWeatherReportService reportService)
    {
        _reportService = reportService;
    }
    
    /// <summary>
    ///     Главная страница
    /// </summary>
    [Route("/")]
    public IActionResult Index()
    {
        return View();
    }
    
    /// <summary>
    ///     Просмотр архивов
    /// </summary>
    [Route("/reports")]
    public async Task<IActionResult> ListView(WeatherReportQuery query)
    {
        var reports = await _reportService.ListAsync(query);
        return View("ListView", reports);
    }
    
    /// <summary>
    ///     Загрузка архивов
    /// </summary>
    [HttpPost]
    [Route("/upload")]
    public async Task<IActionResult> UploadFiles(List<IFormFile> files)
    {
        foreach (var file in files)
        {
            using var ms = new MemoryStream();
            await file.CopyToAsync(ms);
        
            var fileBytes = ms.ToArray();

            try
            {
                await _reportService.UploadExcelReportAsync(fileBytes);
            }
            catch (InvalidOperationException ex)
            {
                return View("UploadFile", ex.Message);
            }
        }

        return View("UploadFile");
    }
    
    /// <summary>
    ///     Загрузка архивов
    /// </summary>
    [HttpGet]
    [Route("/upload")]
    public IActionResult Upload()
    {
        return View("UploadFile");
    }
}

WeatherExcelStorage.Core/Views/Shared/_BaseLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Weather</title>
    <link href="/styles/lib.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    @RenderSection("Css", false)
</head>
<body>
@RenderBody()

@RenderSection("Scripts", false)
</body>
</html>

WeatherExcelStorage.Core/Views/Shared/_Layout.cshtml
@{
    Layout = "_BaseLayout";
}

<section class='wrapper'>
    <div class='hero'>
    </div>
    <div class='content'>
        @RenderBody()
    </div>
</section>

@section Css {
    @await RenderSectionAsync("Css", false)
}

@section Scripts
{
    @await RenderSectionAsync("Scripts", false)
}

WeatherExcelStorage.Core/Views/WeatherReport/Index.cshtml
@{
    ViewBag.Title = "Weather";
    Layout = "_Layout";
}

<h1 class='h1--scalingSize'>Погодные отчеты</h1>
<div class="frame">
    <a class="custom-btn btn" href="@Url.Action("ListView")"><span>Просмотр архивов</span></a>
    <a class="custom-btn btn" href="@Url.Action("Upload")"><span>Загрузка архивов</span></a>
</div>


@section Css {
    <link href="/styles/index.css" rel="stylesheet" type="text/css" />
}

WeatherExcelStorage.Core/Views/WeatherReport/ListView.cshtml
@using Microsoft.OpenApi.Extensions
@using WeatherExcelStorage.Api.Attributes
@model WeatherExcelStorage.Api.Models.PagedList<WeatherExcelStorage.Api.Models.WeatherReport, WeatherExcelStorage.Api.Models.Requests.WeatherReportQuery>

@{
    ViewBag.Title = "Просмотр";
    Layout = "_BaseLayout";
    var pages = Model.Total / Model.Request.Max + 1;
    var current = Model.Request.Skip / Model.Request.Max;
    var start = current - 1;
    if (start <= 0)
    {
        start = 1;
    }

    var end = start + 5;
    if (end >= pages)
    {
        end = pages;
    }
}

<div class="table-container" style="margin: 20px auto; margin-top: @(60 * Model.Items.Length / 20)%;">
    <input type="text" name="daterange" value="@Model.Request.From?.ToString("MM/dd/yyyy") - @Model.Request.To?.ToString("MM/dd/yyyy")" />
    <table id="table" class="table table-hover table-mc-light-blue">
        <thead>
        <tr>
            <th>ID</th>
            <th>Дата</th>
            <th>Температура воздуха</th>
            <th>Облачность</th>
            <th>Точка росы</th>
            <th>Атмосферное давление</th>
            <th>Направление ветра</th>
            <th>Скорость ветра</th>
            <th>Облачность</th>
            <th>Нижняя граница облачности</th>
            <th>Горизонтальная видимость</th>
            <th>Погодные условия</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var report in Model.Items)
        {
            <tr>
                <td>@report.Id</td>
                <td>@report.DateTime.ToString("yyyy-MM-dd HH-mm")</td>
                <td>@report.AirTemperature</td>
                <td>@report.Humidity</td>
                <td>@report.DewPoint</td>
                <td>@report.AirPressure</td>
                <td>@string.Join(", ", report.WindDirection.Select(d => d.GetAttributeOfType<NameAttribute>().Name))</td>
                <td>@report.WindSpeed</td>
                <td>@report.Overcast</td>
                <td>@report.LowOvercastPoint</td>
                <td>@report.HorizontalSight</td>
                <td>@report.WeatherConditions</td>
            </tr>
        }
        </tbody>
    </table>
    <div class="pagination">
        @if (current > 0)
        {
            <a href="@Url.Action("ListView", new {max = Model.Request.Max, skip = (current - 1) * Model.Request.Max, from = Model.Request.From, to = Model.Request.To})" class="arrow button" id="prevPage">← <span class="nav-text">PREV</span></a>
        }
        <div class="pages">
            @for (var i = start; i < end && i > 0; i++)
            {
                <a href="@Url.Action("ListView", new {max = Model.Request.Max, skip = (i - 1) * Model.Request.Max, from = Model.Request.From, to = Model.Request.To})" class="page-number @(current == i - 1 ? "active" : "")">@i</a>
            }
        </div>
        @if (current == pages)
        {
            <a href="@Url.Action("ListView", new {max = Model.Request.Max, skip = (current + 1) * Model.Request.Max, from = Model.Request.From, to = Model.Request.To})" class="arrow button" id="nextPage"><span class="nav-text">NEXT</span> →</a>
        }
    </div>
</div>

@section Css {
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
}

@section Scripts
{
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <script>
$(function() {
  $('input[name="daterange"]').daterangepicker({
    opens: 'left'
  }, function(start, end, label) {
    window.location.href = `@Url.Action("ListView")?from=${start.format('YYYY-MM-DD')}&to=${end.format('YYYY-MM-DD')}&max=@Model.Request.Max&skip=@Model.Request.Skip`;
  });
});
</script>
}

WeatherExcelStorage.Core/Views/WeatherReport/UploadFile.cshtml
@model string?

@{
    ViewBag.Title = "Загрузка";
    Layout = "_Layout";
}

<h1 class='h1--scalingSize'>Загрузка Excel-файлов</h1>
<p style="color: darkred">
	@Model
</p>
<div class="container">
	@using (Html.BeginForm("UploadFiles", "WeatherReport", FormMethod.Post, new { @enctype="multipart/form-data" })) 
	{
		<div>
		    <label for="upload">
    			<input type="file" name="files" id="upload" multiple>
    			Upload Files
		    </label>
		</div>
		<div class="files">
		    <h2>Files Selected</h2>
		    <ul></ul>
		</div>
		<input type="submit" value="Submit" name="submit" id="submit"/>
	}
</div>

@section Css {
    <link href="/styles/uploader.css" rel="stylesheet" type="text/css" />
}

@section Scripts {
	<script>
    let state = {};
    
    function updateState(newState) {
    	state = { ...state, ...newState };
    	console.log(state);
    }
    
    $("input").change(function(e) {
    	let files = document.getElementsByTagName("input")[0].files;
    	let filesArr = Array.from(files);
    	updateState({ files: files, filesArr: filesArr });
    
    	renderFileList();
    });
    
    $(".files").on("click", "li > i", function(e) {
    	let key = $(this)
    		.parent()
    		.attr("key");
    	let curArr = state.filesArr;
    	curArr.splice(key, 1);
    	updateState({ filesArr: curArr });
    	renderFileList();
    });
    
    $("form").on("submit", function(e) {
    	console.log(state);
    	renderFileList();
    });
    
    function renderFileList() {
    	let fileMap = state.filesArr.map((file, index) => {
    		let suffix = "bytes";
    		let size = file.size;
    		if (size >= 1024 && size < 1024000) {
    			suffix = "KB";
    			size = Math.round(size / 1024 * 100) / 100;
    		} else if (size >= 1024000) {
    			suffix = "MB";
    			size = Math.round(size / 1024000 * 100) / 100;
    		}
    
    		return `<li key="${index}">${
    			file.name
    		} <span class="file-size">${size} ${suffix}</span><i class="material-icons md-48">delete</i></li>`;
    	});
    	$("ul").html(fileMap);
    }

	</script>
}